name: nf-reclaim

channels:
    - conda-forge
    - bioconda

dependencies:
    - python==3.12
    - pip
    - conda-forge::jq
    - conda-forge::duckdb-cli
    - bioconda::diamond
    - bioconda::taxonkit
    - pip:
        - "carabiner-tools[pd,mpl]>=0.0.4"
        - "numpy"
        - "scikit-learn"
        - "schemist>=0.0.4.post1"
        - "seaborn"
        - "umap-learn>=0.5.7"
        